# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25e27894e612364c8c0eff2ad1bb184848a648828fbc7ba51b6dd17af577faeb7761d92a659f3838dcc9f498e7186abbf4bfc7b223faa517c747031af92ce035

test:
  secret_key_base: 7f9f4c85a0be12bce5f9a9e492614f7004a7f1513ad31afa0e0081b02379421ecb2c5e107ccc052d74ef11ebb1019883447c26dfecf2872c4dae9ed14adce006

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
